#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=29gb,walltime=0:15:00
#PBS -N bl.freesurfer

[ ! -f dwi/dwi.nii.gz ] && time singularity exec -e docker://brainlife/amico:2.1b ./run.py

[ ! -f dwi/dwi.bvecs ] && echo "failed" && exit 1 || echo "complete" && exit 0
