#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=32gb,walltime=1:00:00
#PBS -N app-split-dwi-volumes

set -x
set -e

# [ ! -f dwi/dwi.nii.gz ] && time singularity exec -e docker://brainlife/amico:2.1b ./run.py
time singularity exec -e docker://brainlife/mrtrix3:3.0.2 ./run.sh

[ ! -f output/dwi.bvecs ] && echo "failed" && exit 1 || echo "complete" && exit 0
