#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=20gb,walltime=0:15:00
#PBS -N app-split-dwi-volumes

set -x
set -e

[ ! -f dwi/dwi.nii.gz ] && time singularity exec -e docker://brainlife/amico:2.1b ./run.py

[ ! -f dwi/dwi.bvecs ] && echo "failed" && exit 1 || echo "complete" && exit 0
